version: '3'
services:
  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    command: npm start